
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action GameAction;
	
	private global::Gtk.Action NewGameAction;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action ExitAction;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar TopMenu;
	
	private global::Gtk.DrawingArea da;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.GameAction = new global::Gtk.Action ("GameAction", global::Mono.Unix.Catalog.GetString ("Game"), null, null);
		this.GameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game");
		w1.Add (this.GameAction, null);
		this.NewGameAction = new global::Gtk.Action ("NewGameAction", global::Mono.Unix.Catalog.GetString ("New game"), null, null);
		this.NewGameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New game");
		w1.Add (this.NewGameAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitAction = new global::Gtk.Action ("ExitAction", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Backgammon by Horatiu");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 720;
		this.DefaultHeight = 624;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='TopMenu'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/><menuitem name='AboutAction' action='AboutAction'/></menu><menu name='GameAction' action='GameAction'><menuitem name='NewGameAction' action='NewGameAction'/></menu></menubar></ui>");
		this.TopMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/TopMenu")));
		this.TopMenu.Name = "TopMenu";
		this.vbox1.Add (this.TopMenu);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.TopMenu]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.da = new global::Gtk.DrawingArea ();
		this.da.Name = "da";
		this.vbox1.Add (this.da);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.da]));
		w3.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ExitAction.Activated += new global::System.EventHandler (this.OnExitActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.da.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnDaButtonReleaseEvent);
		this.da.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnDaButtonPressEvent);
		this.da.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnDaMotionNotifyEvent);
	}
}
